### ISSUE TITLE
npm module is not unit tested

### ISSUE THREAD

**Issue by kt3k** [capsidjs/capsid#215]
While npm module version can pass [todomvc2](https://github.com/capsidjs/todomvc2) testing, the unit tests of capsid can't be executed because of strange transpilation flaw in dnt.

When we use `super.method()` call in private method, the private method is transpiled as independent function, not a method. So that makes `super` call invalid, and our test cases can't run.

**Comment by dsherret** [comment]
Seems like a TypeScript bug: https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmEAu0DeBYAUNaTFIAoBKNLHHYAewDsJKR4A6ESgcwIFYiBuM6AXyyDMWUJBgB5JAAt4AJ2jwAHnmoATGAmSls0KrSRyArsCSU5xHeWgQjAB3nFeunDICWERgGI8yJ32E+H3xLDBcbe3lGX0IeAKEgA -- https://github.com/microsoft/TypeScript/issues/44515

By the way, I think you can just do `"deno": "dev"` to make the deno shim a dev dependency. The `Deno` namespace is only used in the tests, correct?

**Comment by kt3k** [comment]
> By the way, I think you can just do "deno": "dev" to make the deno shim a dev dependency. The Deno namespace is only used in the tests, correct?

Right, thanks! Updated.

> Seems like a TypeScript bug:

Oh, that's unfortunate...

**Comment by kt3k** [comment]
The issue only happened in deno_dom. I used `redirects` feature of dnt and replaced dom polyfill with jsdom in node.js environment. Now all test cases pass with node.js version.
